# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_epidemic <- function(id, simulation_length, population, seed_rate, seed_length, R0, ifr, shape_gt, rate_gt, shape_ip, rate_ip, meanlog_i2d, sdlog_i2d, prob_detection_cases, prob_detection_deaths, col_names, features_matrix, effects, initial_state_ = NULL) {
    .Call(`_episim_simulate_epidemic`, id, simulation_length, population, seed_rate, seed_length, R0, ifr, shape_gt, rate_gt, shape_ip, rate_ip, meanlog_i2d, sdlog_i2d, prob_detection_cases, prob_detection_deaths, col_names, features_matrix, effects, initial_state_)
}

